---
# General values
#
# Set cluster names ... Unfortunately the openshift-gitops operator keeps
# removing the secret of the *mgmtclustername (local cluster),
# therefor we switch ti list generator
# https://issues.redhat.com/browse/GITOPS-1777
mgmt-cluster: &mgmtcluster https://kubernetes.default.svc
mgmt-cluster-name: &mgmtclustername in-cluster
production-cluster: &prodcluster https://api.ocp.ispworld.at:6443
production-cluster-name: &prodclustername prod

repourl: &repourl 'https://github.com/tjungbauer/Servicemesh-Lab'
repobranch: &branch main

argocd_namespace: gitops

applications:
  lab.00-deploy-servicemesh-operators:
    enabled: true
    description: Deploy required ServiceMesh operators
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.00_Deploy_Service_Mesh_Operators/
      repourl: *repourl
      targetrevision: *branch

  lab.01-deploy-bookinfo:
    enabled: true
    description: Deploy bookinfo demo app
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.01_Deploy_Plain_Bookinfo_App/
      repourl: *repourl
      targetrevision: *branch

  lab.02-create-service-mesh:
    enabled: true
    description: Create ServiceMesh system
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.02-Create-Service-Mesh/
      repourl: *repourl
      targetrevision: *branch

  lab.03-create-ingress-gateway:
    enabled: true
    description: Deploy ingress gateway
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.03-Create-Ingress-Gateway/
      repourl: *repourl
      targetrevision: *branch
  
  lab.04-create-simple-virtualservice:
    enabled: true
    description: Deploy VirtualService
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.04-Create-Simple-VirtualServices/
      repourl: *repourl
      targetrevision: *branch

  lab.05-virtual-services-based-on-user:
    enabled: true
    description: Deploy VirtualService based on User
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.05-VirtualServices-based-on-User/
      repourl: *repourl
      targetrevision: *branch

  lab.06-a-create-service-entry:
    enabled: true
    description: Deploy ServiceEntry
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.06-A-Create-ServiceEntry/
      repourl: *repourl
      targetrevision: *branch

  lab.06-b-create-service-entry:
    enabled: true
    description: Deploy ServiceEntry
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.06-B-Create-ServiceEntry/
      repourl: *repourl
      targetrevision: *branch

  lab.07-create-egressgateway:
    enabled: true
    description: Deploy Egress Gateway
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.07-Create-EgressGateway/
      repourl: *repourl
      targetrevision: *branch

  lab.08-egressgateway-https-origination:
    enabled: true
    description: Deploy Egress Gateway https origination
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.08-EgressGateway-HTTPS-Origination/
      repourl: *repourl
      targetrevision: *branch

  lab.09-canary-deployment:
    enabled: true
    description: Test Canary Deployment
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.09-A-Canary-Deployment/
      repourl: *repourl
      targetrevision: *branch

  lab.09-mirror-traffic:
    enabled: true
    description: Test traffic mirroring
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.09-B-Mirroring-Traffic/
      repourl: *repourl
      targetrevision: *branch

  lab.09-c1-fault-injection:
    enabled: true
    description: Test fault injection
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.09-C1-Fault-Injection/
      repourl: *repourl
      targetrevision: *branch

  lab.09-c2-slow-connection:
    enabled: true
    description: Test Slow Connections
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.09-C2-Slow-Connection/
      repourl: *repourl
      targetrevision: *branch

  lab.10-force-mtls:
    enabled: true
    description: Deploy mTLS
    server: *mgmtcluster
    project: servicemesh-lab
    source:
      path: Lab.10-Force-mTLS/
      repourl: *repourl
      targetrevision: *branch
